spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inac1
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true