spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    xa:
      first:
        url: jdbc:mysql://localhost:3306/inac1
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.MysqlXADataSource
        unique-resource-name: first
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

      second:
        url: jdbc:mysql://localhost:3306/coupon_example
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.MysqlXADataSource
        unique-resource-name: second
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl