spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inac1
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

camel:
  servlet:
    mapping:
      enabled: true
      context-path: /*
  lra:
    enabled: true
    coordinator-url: http://localhost:8088
    local-participant-url: http://host.docker.internal:8080
    local-participant-context-path: /lra-participant