server:
  port: 8001

camel:
  servlet:
    mapping:
      enabled: true
      context-path: /*
  lra:
    enabled: true
    coordinator-url: http://localhost:8088
    local-participant-url: http://host.docker.internal:8001
    local-participant-context-path: /lra-participant